### ISSUE TITLE
Add lazy load/ ghost rendering animation for the images that are currently loading

### ISSUE THREAD

**Issue by sakshamk-neuradynamics** [ruds18/photoglyph#1]
# Suggestion
- ## What I observed when I opened the website
    The first time I visited the website only names were being displayed and no pictures which for a minute made me wonder if the website is broken. I waited for a bit and the images started rendering it was due to the time that took to fetch all those images.
- ## The suggestions I'd like to propose
     - ### Add a loading screen to the website
         Adding a loading screen such that the user has to wait to interact with the website until everything is loaded. Which delays user interaction
     - ### Make a Skeleton Screen
         A much more modern solution used by many websites such as LinkedIn where they use a skeleton element instead while the data is being rendered in place of the actual element

**Comment by ruds18** [comment]
Thanks for the feedback!
